### PR TITLE
Check all requirements for security vulnerabilities

### PR DESCRIPTION
**Pull request by vkurup**
[ch5159]

This checks the packages in the currently active virtualenv. It's also possible to check packages based on a requirements.txt file, in case we only want to check production requirements, for example.

I expect this to fail CI because of the pysaml issue: clubhouse 5204

### CODE REVIEW

**Comment by vkurup** [comment]
During this week's standup, I asked whether to use the online service or to run the checks on Circle CI, and was asked to use CircleCI. I'm happy to do it any way that you want, but I'll need repo access to set up the online service.

This check takes 0.9 seconds on my laptop:
```
(etools) vkurup@caktus020:~/dev/etools-infra(master) $ time safety check
╒══════════════════════════════════════════════════════════════════════════════╕
│                                                                              │
│                               /$$$$$$            /$$                         │
│                              /$$__  $$          | $$                         │
│           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           │
│          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           │
│         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           │
│          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           │
│          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           │
│         |_______/  \_______/|__/     \_______/   \___/   \____  $$           │
│                                                          /$$  | $$           │
│                                                         |  $$$$$$/           │
│  by pyup.io                                              \______/            │
│                                                                              │
╞══════════════════════════════════════════════════════════════════════════════╡
│ REPORT                                                                       │
│ checked 167 packages, using default DB                                       │
╞════════════════════════════╤═══════════╤══════════════════════════╤══════════╡
│ package                    │ installed │ affected                 │ ID       │
╞════════════════════════════╧═══════════╧══════════════════════════╧══════════╡
│ pysaml2                    │ 4.4.0     │ <=4.4.0                  │ 35700    │
│ pysaml2                    │ 4.4.0     │ <=4.4.0                  │ 35699    │
╘══════════════════════════════════════════════════════════════════════════════╛

real	0m0.940s
user	0m0.552s
sys	0m0.032s
```

**Comment by saxix** [comment]
sorry, maybe I missed that agreement. If I got the PR, now the CI will fail any time the requirements have some security issue, is this correct ?

**Comment by vkurup** [comment]
No worries! That is correct. I also mentioned that during the meeting. If that happens and we are unable to upgrade for whatever reason, we will have to manually disable the check, by commenting it out (or ignoring it's exit code).

**Comment by vkurup** [comment]
I just 'requested UNICEF access' via the pyup.io interface, in case we want to use the online service instead. So someone at UNICEF should be getting an email shortly :)

**Comment by ntrncic** [comment]
@vkurup someone approved the pyup github access

**Comment by vkurup** [comment]
Great! I'll close this for now and let you know if I need any other help setting it up.

**Pull request closed without merging**
