### PR TITLE
Feature activity stream [WIP]

### PR DESCRIPTION
**Pull request by robertavram**
@n1207n making a standing pr for your branch (as required by the contributing guide to access changes more easily)

### CODE REVIEW

**Comment by n1207n** [comment]
@robertavram I think activity stream logic + test cases are done for Agreement Django model. Feel free to take a look and let me know if you have any comments!

**Comment by robertavram** [comment]
@n1207n this looks solid.. I need to play around with it locally.. i think it can be used nicely

**Comment by robertavram** [comment]
@n1207n can you update this from develop make sure it works.. might have to re-write tests.. thanks!

**Comment by n1207n** [comment]
@robertavram I had to go through a huge merge conflict but it seems to resolved now. Also I fixed my test cases for activity stream.

**Pull request merged**
