### PR TITLE
utility functionality refactoring

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by domdinicola** [comment]
this is just reshaping the utility functions within a more organized package

**Comment by ntrncic** [comment]
was this discussed with anyone?

**Comment by domdinicola** [comment]
nope... this was my initiative to better structure the code

**Comment by robertavram** [comment]
I don't know what i need to look for here.. refactoring? 90 pages, I can't review this.. Let's talk about it and split it in smaller chunks.

**Pull request closed without merging**
