### PR TITLE
Auditor portal minor updates

### PR DESCRIPTION
**Pull request by maximlomakin**
Changes from tasks:
- https://trello.com/c/FNq1TumG/168-in-spot-check-report-relabel-recommendation-to-finding-and-recommendation
- https://trello.com/c/5T5PvQah/160-relabel-shared-ip-with-to-shared-audit-with
- https://trello.com/c/NH7bb0sG/164-please-rename-ice-form-to-ice
- https://trello.com/c/UK8n1kUQ/169-micro-assessment-remove-n-a-from-report-in-overall-risk-assessment-dropdown
- https://trello.com/c/URcshCNE/170-add-joint-audit-as-a-filter-in-the-list-view

### CODE REVIEW

**Comment by ntrncic** [comment]
is this ready?

**Comment by ntrncic** [comment]
@maximlomakin @roman-karpovich if you would like this PR to be reviewed and merged please label it READY

**Comment by roman-karpovich** [comment]
@ntrncic okay, of course! we'll mark this as ready after passing our internal QA.

**Comment by roman-karpovich** [comment]
QA is almost finished, so i'll close this PR in favor to #1366 as more wide.

**Pull request closed without merging**
