### PR TITLE
Squash migrations

### PR DESCRIPTION
**Pull request by ntrncic**

### CODE REVIEW

**Comment by robertavram** [comment]
#247

**Comment by robertavram** [comment]
@ntrncic please update your comment to include all fake migrations for all apps....

**Comment by ntrncic** [comment]
@robertavram some apps are dependent on others therefore only the 5 mentioned need to be run. 
if you run the other apps it just says no migrations to be applied.

**Comment by robertavram** [comment]
cool.. waiting for tomorrow afternoon... let's try together

**Pull request merged**
