### PR TITLE
Refactor partners/tasks.py and add tests

### PR DESCRIPTION
**Pull request by caktus-philip**
Refactor `partners/tasks.py` and add tests (using lots of mocking).

`partners/tasks.py` was untestable as written. It used a decorator (called `task_decorator()`) to execute setup code common to each task. However, the decorator executed as soon as `partners.tasks` was imported. (That’s the nature of decorators.) As soon as any test imported it, the decorator failed --
```
  File "/code/EquiTrack/partners/tests/test_tasks.py", line 1, in <module>
    import partners.tasks
  File "/code/EquiTrack/partners/tasks.py", line 48, in <module>
    def agreement_status_automatic_transition(admin=None, workspace=None, **kwargs):
  File "/code/EquiTrack/partners/tasks.py", line 31, in task_decorator
    admin = User.objects.get(username=settings.TASK_ADMIN_USER)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
```

I refactored `tasks.py` to remove the decorator. The code that was in the decorator is unfortunately now repeated in every task, so this PR is step backwards from a  DRY perspective. New code consists of a task (very simple) plus a helper  function (where all the work is done) for each task.

Notable changes -- 
 - Added tests! :-)
 - Added docstrings for tasks
 - Fixed a couple of bugs in `get_intervention_context()` (bad81c1a2bfe80e77e804f20849a9e0813cbe7cc)
 - Fixed indentation in `agreement_status_automatic_transition()` and `intervention_status_automatic_transition()` which were double indented for some reason. (harmless but made the `git diff` messy)
 - Fixed the same bug in `agreement_status_automatic_transition()` and `intervention_status_automatic_transition()` which would cause logging of  "bad" ids to fail. (4642d0c979450ea91bef34493e89951d11ee3c32)
 - Fixed an incorrect logger msg  (changed 'Starting agreement...' ==> 'Starting intervention...') (f9b0b64cb178a5326146105e7c5aaeb1e5552b30)
 - Added the constant `_INTERVENTION_ENDING_SOON_DELTAS` to increase visibility of magic numbers (4883ed80c0eeb7ad1c8d539a36f8614d5247949e)
 - refactor the core of `intervention_notification_ending()` to not iterate over a dict to make it testable. (4883ed80c0eeb7ad1c8d539a36f8614d5247949e)

### CODE REVIEW

**Comment by ntrncic** [comment]
@caktus-philip please update branch.

**Comment by robertavram** [comment]
@caktus-philip 👍  👍  👍  there was another issue where because the @task was decorated the tasks were not properly registered with celery.. (my bad- meant to fix it.. didn't get to it before vacay... awesome that you found the flaw!)

thx!!!
let us know when this is ready.

**Comment by caktus-philip** [comment]
Should have labelled this question. The work is complete except for one part, which is that I have this URL hardcoded in the tests and I'd rather use Django `reverse()` to get it. I can't figure out how to reverse the URL though. I can't find the pattern that governs this URL --
https://github.com/unicef/etools/blob/add-partners-task-tests/EquiTrack/partners/tasks.py#L34

**Comment by caktus-philip** [comment]
@ntrncic branch updated

**Pull request merged**
