### PR TITLE
Attachments upload

### PR DESCRIPTION
**Pull request by reinbach**
[ch4172]

Handle attachment upload functionality.

To enable a serializer to handle setting attachment, do the following steps;
1. Add the `AttachmentSerializerMixin` to the serializer
2. Add the field as a `AttachmentSingleFileField()` to the serializer

### CODE REVIEW

**Comment by ntrncic** [comment]
@reinbach please redo migrations as they've been reset

**Comment by reinbach** [comment]
@ntrncic when you say redo, are you saying squash them or just get them in sequence?
If the later, that has been done

**Comment by domdinicola** [comment]
@reinbach

**Comment by ntrncic** [comment]
@reinbach please resolve conflict. I'll make sure to test this sprint.

**Comment by reinbach** [comment]
@ntrncic could we please reopen this pull request, I accidentally deleted the branch :(

**Comment by ntrncic** [comment]
reopenning

**Pull request closed without merging**
