### PR TITLE
Make char and text fields not nullable where possible

### PR DESCRIPTION
**Pull request by dpoirier**
https://github.com/unicef/etools-issues/issues/652

### CODE REVIEW

**Comment by domdinicola** [comment]
@dpoirier please update and resolve conflicts

**Comment by dpoirier** [comment]
@domdinicola this has been updated.

**Comment by dpoirier** [comment]
Merge conflicts have been resolved again.

**Comment by dpoirier** [comment]
FYI, I'll postpone resolving merge conflicts until I'm told that this is near to being merged.  That'll reduce repeatedly doing the same work.

**Comment by ntrncic** [comment]
we will have to maybe merge this one after the other PR you made with migrations. please resolve conflicts

**Comment by dpoirier** [comment]
[ch1041]

**Comment by domdinicola** [comment]
@dpoirier can you generate again the migration? we do prefer to have migration in sequence and avoid merge migrations.. thanks

**Comment by ntrncic** [comment]
we will postpone this PR until migrations are squashed

**Comment by ntrncic** [comment]
@dpoirier
Redo migrations again

**Comment by dpoirier** [comment]
@ntrncic migrations have been redone.

**Comment by ntrncic** [comment]
please resolve conflicts

**Comment by dpoirier** [comment]
@ntrncic updated

**Pull request merged**
