### PR TITLE
Users v3 API changes

### PR DESCRIPTION
**Pull request by csabadenes**
- fix users list URL regex
 - restrict access to users list to staff and superuser
 - add namespace to users v3 url group

### CODE REVIEW

**Comment by csabadenes** [comment]
connects unicef/etools-issues#937

**Comment by caktus-philip** [comment]
👍 I'm working on the same TODO for other parts of the `users` API; this will help.

**Comment by csabadenes** [comment]
@caktus-philip, i wanted to fix the users list URL regex, but since there was a TODO on the same line, i addressed that too. I did not know you are already working on that, sorry. I tried to limit the changes to the users list endpoint, hopefully the conflicts will be bearable.

**Comment by caktus-philip** [comment]
@csabadenes No worries at all. I wanted to fix a 'simple' TODO and got distracted by other things I found in `users`. The same TODO exists in v1 of the URLs and I can use your permission class to fix that.

**Comment by csabadenes** [comment]
Hi @ntrncic , i am marking this ready, those tests already should be there(as we discussed on slack).

**Pull request merged**
