### PR TITLE
[Field Monitoring] data collection structure update

### PR DESCRIPTION
**Pull request by roman-karpovich**
The main goal is to re-use structure for offline data collection

### CODE REVIEW

**Comment by roman-karpovich** [comment]
added simple usage example: ContactBookExampleTestCase
resulting structure json: https://gist.github.com/roman-karpovich/84f253f54d7a84e582840a5362c92576

**Comment by robertavram** [comment]
This is for step 2... generalizing.. it's most likely going to be useful in the next couple of months.. for now, it would be great to keep current structure.. just nested in one call rather than for each card.

Frontend logic is already built for that.. we could keep it simple for now.

**Comment by robertavram** [comment]
So far.. everything looks wonderful!

**Comment by robertavram** [comment]
@reinbach concurs!

**Pull request merged**
