### PR TITLE
Termination and Contingency

### PR DESCRIPTION
**Pull request by robertavram**

### CODE REVIEW

**Comment by acory** [comment]
@robertavram There might be a bug on this PR , on save PD (without changing anything related to termination) I get `Cannot change fields while in draft: termination_doc`. Can you check?

**Comment by robertavram** [comment]
are you trying to change termination_doc? can you check the post request?

**Comment by acory** [comment]
No. One easy way to reproduce:
Go to existing Draft PD that already has start and end date , do not modify anything, hit Save.
Request Payload is `{}`, Response is `Cannot change fields while in draft: termination_doc`

**Comment by robertavram** [comment]
I can;t reproduce it for some reason.. what Front End branch should i use?

**Comment by robertavram** [comment]
@acory I've changed a few things on this branch
if you haven't run migrations yet you're good.. otherwise you might have to dump db and restore

I'll share a recent db with you

**Comment by acory** [comment]
FE branch feature--pd-termination. Already ran migrations..

**Pull request merged**
