### PR TITLE
[ch9365] rename EquiTrack app to core

### PR DESCRIPTION
**Pull request by domdinicola**
we need to run "python manage.py migrate core --fake"

### CODE REVIEW

**Comment by domdinicola** [comment]
[ch9365]

**Comment by robertavram** [comment]
@domdinicola conflicts pls

**Comment by domdinicola** [comment]
run in shell

from django.db import connection
with connection.cursor() as cursor:
    cursor.execute('ALTER TABLE "EquiTrack_domain" RENAME TO core_domain;')

**Comment by domdinicola** [comment]
@reinbach can you review again + my comment

**Comment by robertavram** [comment]
> run in shell
> 
> from django.db import connection
> with connection.cursor() as cursor:
> cursor.execute('ALTER TABLE "EquiTrack_domain" RENAME TO core_domain;')
> 
> python manage.py migrate core --fake
> 
> THEN
> 
> python manage.py migrate_schemas --noinput

can't this be a migration?

**Comment by domdinicola** [comment]
I think is better like this.. the migration is only for public schema

**Comment by domdinicola** [comment]
we will need to run this
python manage.py migrate_schemas core 0001 --fake

**Pull request merged**
