### PR TITLE
[FM] Export for visits page

### PR DESCRIPTION
**Pull request by roman-karpovich**
Story details: https://app.shortcut.com/unicefetools/story/37411

### CODE REVIEW

**Comment by robertavram** [comment]
needs translations conflict resolution

**Comment by roman-karpovich** [comment]
> needs translations conflict resolution

updated

**Comment by robertavram** [comment]
> > needs translations conflict resolution
> 
> updated

happened again. my bad.

**Comment by roman-karpovich** [comment]
updated translations

**Pull request merged**
