### PR TITLE
Test new ci

### PR DESCRIPTION
**Pull request by robertavram**

### CODE REVIEW

**Comment by czue** [comment]
@robertavram :white_check_mark: 

[the directory just wasn't there](https://github.com/unicef/etools/pull/905/commits/d45d2d0a64e187a45a4711761c4faf5d83f46003)

**Comment by robertavram** [comment]
blah... waiting to get some sort of help on this... trying to avoid using docker-machine
https://discuss.circleci.com/t/accessing-database-inside-a-docker-container/16973

**Comment by robertavram** [comment]
@czue feel free to pick this up if you want to.,.. if not I will some other time...

**Comment by czue** [comment]
sure, i'll bang on it a bit and see if i can get anywhere.

**Comment by czue** [comment]
@robertavram :white_check_mark: :joy:

**Comment by czue** [comment]
Like we discussed, had to spin up a new db container inside the other container. But it finally works.

**Comment by czue** [comment]
@robertavram  :white_check_mark:

**Pull request merged**
