### PR TITLE
Remove LinkedLocation, Governorate, Locality, Region models

### PR DESCRIPTION
**Pull request by ilcsik**
Admin needs to be checked

### CODE REVIEW

**Comment by ntrncic** [comment]
@ilcsik looks good, is it finished?

**Comment by ilcsik** [comment]
@ntrncic yes

**Comment by ilcsik** [comment]
Resolves #251

**Comment by robertavram** [comment]
looks ok.. needs updating and migrations need to be re-written..
@ntrncic test locally.. make sure it works ok

**Comment by ilcsik** [comment]
@robertavram Merged develop and fixed conflicts. How would you rewrite migrations? Only the last/conflicting ones or back to a certain point? 

I merged them with --merge for now just to see if it's all ok when running tests.

**Comment by ilcsik** [comment]
@robertavram migrations consolidated

**Pull request merged**
