### PR TITLE
Update answer attachment within create function

### PR DESCRIPTION
**Pull request by reinbach**

### CODE REVIEW

**Comment by robertavram** [comment]
@reinbach any ticket relating to this? do you remember what the issue was here?

**Comment by reinbach** [comment]
> @reinbach any ticket relating to this? do you remember what the issue was here?

This was me attempting to fix an issue that was happening in prod. I think we can close this PR, as we want with requiring the FE to make another request. @ntrncic thoughts?

**Comment by robertavram** [comment]
@reinbach there's an issue with attachments that is being reported in prod.. but I have no idea what it is.. do you remember the issue that we're trying to fix here?

**Comment by reinbach** [comment]
@robertavram the issue was that the response from the BE did not have the updated data for the attachment. But a refresh did.
This hack was an attempt to make sure the first response did have the updated data.

This issue is not happening locally (or in dev, I believe) just in prod

**Comment by robertavram** [comment]
Fascinating, yeah.. that's not what's being reported. The attachments are
disappearing for some people, apparently, can't reproduce. no idea how this
can happen. I'm getting on a call with a user that's supposedly
experiencing this and I will update after.

**Comment by robertavram** [comment]
nope

**Pull request closed without merging**
