### PR TITLE
Audit reference number moved to db

### PR DESCRIPTION
**Pull request by reinbach**
[ch12761]

See https://github.com/unicef/etools/pull/2412

### CODE REVIEW

**Comment by domdinicola** [comment]
can you update these PRs @reinbach as you did for Action Points

**Comment by reinbach** [comment]
> can you update these PRs @reinbach as you did for Action Points

done

**Comment by domdinicola** [comment]
@reinbach please resolve conflicts and regenerate the migration

**Comment by domdinicola** [comment]
[ch26848]

**Review by domdinicola — APPROVED** [review]

**Pull request merged**
