### PR TITLE
Dictionary iteration methods changed in Python 3

### PR DESCRIPTION
**Pull request by dpoirier**
The dict.iterXXXX() methods from Python 2 are gone in
Python 3, replaced by dict.XXXX() (where XXXX can be
keys, values, or items).

The only way to write code that works in both versions
is to use the `six` helpers: six.iterXXXX(dict).

### CODE REVIEW

**Comment by dpoirier** [comment]
@domdinicola can you fix these tests? Looks like a migration issue: "OperationalError: cannot ALTER TABLE "users_office" because it has pending trigger events"

**Comment by dpoirier** [comment]
Not that I changed anything, but the CI tests passed when run a second time.

**Comment by domdinicola** [comment]
@dpoirier please resolve conflicts

**Comment by dpoirier** [comment]
@domdinicola conflicts have been resolved

**Comment by domdinicola** [comment]
@dpoirier please update the label in order to understand that the pr is ready again and conflict have been resolved

**Pull request merged**
