### PR TITLE
update_audit_permissions cmd: unique_id instead of reference_number

### PR DESCRIPTION
**Pull request by emaciupe**
@domdinicola @robertavram any particular reason why ```unique_id``` was also introduced  for ```reference_number``` ? should we have this consistent across the project ?

### CODE REVIEW

**Comment by emaciupe** [comment]
[ch28876]

**Comment by domdinicola** [comment]
@emaciupe we migrated recently "reference_number" from property to field, most probably this caused the issue

**Comment by domdinicola** [comment]
I think we should always use reference_number but this needs to be synchronized with the FE

**Comment by emaciupe** [comment]
> @emaciupe we agreed to use reference_number everywhere

right,  then merging develop into staging will wait until the unique_id is replaced otherwise you will bump into the same bug this PR is for, breaking FAM engagements.

**Comment by domdinicola** [comment]
@emaciupe correct, this need to be coordinated with a front-end PR

**Pull request closed without merging**
