### PR TITLE
Csv export validation tests

### PR DESCRIPTION
**Pull request by ilcsik**

### CODE REVIEW

**Comment by robertavram** [comment]
adding WIP as tests are failing

**Comment by ntrncic** [comment]
@ilcsik why is this still WIP?

**Comment by robertavram** [comment]
@ilcsik please fix the tests or close the PR

**Comment by ilcsik** [comment]
@robertavram it's the redis connection error during docker/CI run. Do you have any idea?

**Comment by ntrncic** [comment]
@ilcsik we are getting errors for tests in t2f because there is no data being return from the endpoints. Please create a travel then test the export response.

**Comment by ilcsik** [comment]
@ntrncic this is something that @simon-the-sloth fixed for my other branch already - for some reason their files getting pulled in in when you pull develop, I couldn't figure out why.

@simon-the-sloth can you please fix this branch as well?

**Comment by robertavram** [comment]
merged in a different PR

**Pull request closed without merging**
