### PR TITLE
Fix t2f mispellings

### PR DESCRIPTION
**Pull request by ewheeler**
refactoring and migration to rename `IteneraryItem` to `ItineraryItem`

also two function names

@simon-the-sloth @torbent please make sure you have a dictionary on hand at Pulilab HQ...

### CODE REVIEW

**Comment by robertavram** [comment]
@ewheeler sorry.. I merged your other branch previously.. could you please resolve conflicts?

**Comment by ewheeler** [comment]
@robertavram sorry should have mentioned the ideal ordering of the PRs!

**Comment by robertavram** [comment]
as per your instruction Evan, closing until we're ready to attack it again :)

**Comment by ewheeler** [comment]
👍

**Pull request closed without merging**
