### PR TITLE
update requirements part 1

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by domdinicola** [comment]
I'll create another PR for DRF

**Comment by robertavram** [comment]
highly recommend against blanked upgrades. I don't have the enough confidence in our tests yet... let's filter through requirements together

**Comment by domdinicola** [comment]
The most of the new requirement are minor or fix releases and I think is really important to upgrade requirements from time to time..
I think we can merge this at the beginning of the sprint, so while we develop we do also test the new requirements.
what do you think @robertavram ?

**Comment by robertavram** [comment]
please comment once you confirm all packages are good to go...

**Comment by domdinicola** [comment]
ready to go!

**Pull request merged**
