### PR TITLE
update permission matrix

### PR DESCRIPTION
**Pull request by simon-the-sloth**
fixes unicef/etools-issues#187

### CODE REVIEW

**Comment by ewheeler** [comment]
this file needs to be reformatted or reorganized or split up somehow. 
its impossible to make sense of a diff with 7891 additions and 5783 deletions

**Comment by ewheeler** [comment]
i think storing as yaml will be easier to diff: https://gist.github.com/ewheeler/38fe6e5ad80a57b7fd26f9de1117a5bc

**Comment by robertavram** [comment]
Hi @simon-the-sloth .. I know that a script runs to generate the permissions matrix.. is there a reference to how you typically run this script and how you generate it?

It would be useful to inculde in a Readme somewhere..

**Comment by simon-the-sloth** [comment]
@robertavram We have an external utility to do it, but not included in the repo.

**Comment by ewheeler** [comment]
@simon-the-sloth please add this utility to the repo

**Comment by robertavram** [comment]
@simon-the-sloth please add the script to the repo.. and also comment in somewhere what are the changes that were addressed by this PR. Also, include comments in the script on how to run it to create the Permissions Matrix

**Pull request merged**
