### PR TITLE
Merge base test classes

### PR DESCRIPTION
**Pull request by reinbach**
FastTenantTestCase and APITenantTestCase merged

See https://github.com/unicef/etools-issues/issues/643

### CODE REVIEW

**Comment by vkurup** [comment]
Heh, this is the work that I've been mentioning is stashed in my local repo waiting for #1102 to get through. :)

I also just looked at #1177 and it looks like @dpoirier  has made a similar change there (but against prp-refactoring). Wondering if we should just go with that? Thoughts?

**Comment by reinbach** [comment]
Ha, oh dear. I didn't even look around to see if this ticket had been worked on, just saw it in "On deck" and it was assigned to me. Not sure which repo is best to go with. Either way there is going to be a bunch of merging to deal with.

I'm fine with which ever direction we want to go with.

**Comment by vkurup** [comment]
Yes, having multiple 'assignees' on a ticket is definitely a confusing situation... I'm also fine with any PR. The code in both look fine to me.

**Comment by reinbach** [comment]
Only thing I would mention is that in Dan's changes we still have the 2 TestCases in place, I think we want to get those merged. So if you does that, then we can get rid of this pull request.

**Comment by ntrncic** [comment]
I agree we should use Dan's PR...

**Pull request closed without merging**
